### ISSUE TITLE
Style the layout of the Docs pages

### ISSUE THREAD

**Issue by cjyabraham** [cjyabraham/grpc#13]
In pulling out html markup from md files, I'm having trouble getting all docs pages to format their content in the center of the page with equal margins.  Here are the problem ones right now:
* http://localhost:1313/docs/
* http://localhost:1313/docs/talks/
* http://localhost:1313/docs/reference/java/generated-code/

A similar point is that on mobile, margins of some pages [are large](https://cjyabraham.github.io/docs/reference/go/generated-code/), on other pages [are small](https://cjyabraham.github.io/blog/hello-pancakes/).  Could we standardize?

**Comment by alexcontini** [comment]
fixed
