### ISSUE TITLE
Add table formatting

### ISSUE THREAD

**Issue by cjyabraham** [cjyabraham/grpc#4]
Improve the formatting of the tables in [this post](http://localhost:1313/blog/2017-08-22-grpc-go-perf-improvements/), [this post](http://localhost:1313/blog/loadbalancing/), [this page](http://localhost:1313/docs/guides/error/) and perhaps other places.  See how it is done on the [live site](https://grpc.io/2017/08/22/grpc-go-perf-improvements.html).

**Comment by alexcontini** [comment]
fixed
